name: build

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        packages: [ '.' ]
        runtest:
          - true
        ocaml-compiler:
          - 4.14
          - 5.2
        include:
          - os: ubuntu-latest
            ocaml-compiler: 4.08
            packages: 'alcotest alcotest-js alcotest-lwt alcotest-mirage'
            opam-local-packages: 'alcotest.opam alcotest-js.opam alcotest-lwt.opam alcotest-mirage.opam'
            runtest: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        if: runner.os != 'Windows'
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: $${ matrix.opam-local-packages }}
          opam-depext-flags: --with-test

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        if: runner.os == 'Windows'
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: $${ matrix.opam-local-packages }}
          opam-depext-flags: --with-test
          opam-repositories: |
            windows-5.0: https://github.com/dra27/opam-repository.git#windows-5.0
            opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
            default: https://github.com/ocaml/opam-repository.git

      - run: |
          opam pin add alcotest-async.dev ./ -n
          opam pin add alcotest-js.dev ./ -n
          opam pin add alcotest-lwt.dev ./ -n
          opam pin add alcotest-mirage.dev ./ -n
          opam pin add alcotest.dev ./ -n

      - run: opam install ${{ matrix.packages }} --with-test --deps-only
      - if: ${{ matrix.runtest }}
        run: opam exec -- dune build @install @check @runtest @runtest-js
